name: aston_math_application
description: A math application for foundation year students to improve their ability at maths at.

publish_to: 'none' # Stops publishing to pub.dev

# Version Number of application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# README.md includes all appropriate havard references for the libraries/text/images below
dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  connectivity_plus: ^1.0.1
  retrofit: ^2.0.0
  json_serializable: ^4.1.3
  flutter_svg: ^0.22.0
  easy_localization: ^3.0.0
  crypto: ^3.0.1
  shared_preferences: ^2.0.6
  jwt_decoder: ^2.0.1
  get_it: ^7.1.3
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.2
  modal_bottom_sheet: ^2.0.0
  firebase_core: ^1.10.0
  firebase_crashlytics: ^2.3.0
  firebase_auth: ^3.2.0
  flutter_local_notifications: ^9.3.1
  firebase_messaging: ^11.2.6
  cloud_firestore: ^3.1.0
  permission_handler: ^8.0.0+2
  flutter_tex: ^4.0.1
  google_nav_bar: ^5.0.5
  cupertino_icons: ^1.0.2
  math_keyboard: ^0.1.4
  progress_state_button: ^1.0.4
  youtube_player_flutter: ^8.0.0
  percent_indicator: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  dialogs: ^0.0.7
  future_progress_dialog: ^0.2.0
  mockito: ^5.0.15
  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.20



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  retrofit_generator: ^2.0.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/emp.png"


flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/font/
    - assets/logo/
  # Logo uses ASAP Family Font.

  fonts:
    - family: Asap
      fonts:
        - asset: assets/font/asap/Asap-Regular.ttf
        - asset: assets/font/asap/Asap-Italic.ttf
          style: italic
        - asset: assets/font/asap/Asap-Regular.ttf
          weight: 400
        - asset: assets/font/asap/Asap-SemiBold.ttf
          weight: 600
        - asset: assets/font/asap/Asap-Bold.ttf
          weight: 700
    - family: AsapCondensed
      fonts:
        - asset: assets/font/asap_condensed/AsapCondensed-Regular.ttf
        - asset: assets/font/asap_condensed/AsapCondensed-Italic.ttf
          style: italic
        - asset: assets/font/asap_condensed/AsapCondensed-Regular.ttf
          weight: 400
        - asset: assets/font/asap_condensed/AsapCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/font/asap_condensed/AsapCondensed-Bold.ttf
          weight: 700

